### ISSUE TITLE
Crashing on my machine

### ISSUE THREAD

**Issue by ArneBachmannDLR** [ohaswin/pyscan#6]
Python 3.11 in a conda environment on Windows, pip installed pyscan-rs:

```
pyscan v0.1.3 | by Aswin (github.com/aswinnnn)
Found 9 dependencies...
|-| fasteners [0.18] -> No vulnerabilities found.
thread 'main' panicked at 'Could not retrive package version.: PipError("could not retrive package version from Pip")', src\scanner\mod.rs:28:69
stack backtrace:
   0:           0x973780 - <unknown>
   1:           0x9cbc1b - <unknown>
   2:           0x965605 - <unknown>
   3:           0x97698f - <unknown>
   4:           0x976647 - <unknown>
   5:           0x9771bf - <unknown>
   6:           0x9770c5 - <unknown>
   7:           0x9742bf - <unknown>
   8:           0x976de0 - <unknown>
   9:           0x9c86a5 - <unknown>
  10:           0x9c8a73 - <unknown>
  11:           0x422bc9 - <unknown>
  12:           0x42ebf8 - <unknown>
  13:           0x4410a5 - <unknown>
  14:           0x447be6 - <unknown>
  15:           0x41cecc - <unknown>
  16:           0x958097 - <unknown>
  17:           0x44524d - <unknown>
  18:           0x4013f8 - <unknown>
  19:           0x40151b - <unknown>
  20:     0x7ffffab07614 - <unknown>
  21:     0x7ffffc0a26a1 - <unknown>
```

Any idea?

**Comment by ohaswin** [comment]
That error occurs when pyscan could not find the package from your `pip`

can you check:

+ wether you have the package installed via pip
+  if not, check your `requirements.txt`/other source if a version is specified along with it

This is because you havent specified a version in your source, so pyscan checks if you have installed it on your machine via pip, and retrives the version from there.
If pyscan could not find a version either from a file or `pip`, this error occurs.
Error handling still needs to be polished a bit but let me know what you find out after you check my above suspicions.

**Comment by ArneBachmannDLR** [comment]
This is bound to happen in conda environments or under recent Ubuntu Python, where packages only occasionally come via pip but via the system's package manager (apt).

While I may have a `requirements.txt` (or actually many of them for different installation options), the eventually used configuration either comes from `pyproject.toml` or from a requirements file injected via a hatch plugin... It can get messy with these many packaging tools available :-D

**Comment by ohaswin** [comment]
it can get messy for sure, I hadn't considered adding support for apt yet because the packages from pypi and apt sometimes have different names, which can lead to error in version detection that could go unnoticed or other misapprehensions.

I reccomend versionizing your configuration for now, but i understand that might not be feasible for everyone.
There's a new feature coming in the next version where you can either answer a prompt or select a flag (`--pip`,`--source`,`--latest`) if you want to default to either pip, configuration or the latest stable version specified on pypi, which might be of some help.

**Comment by ArneBachmannDLR** [comment]
Here is a part of my `pyproject.toml`, isn't that enough version information? If any of those wasn't available on pip, shouldn't pyscan at least tell me which is the culprit?

```toml
[project]
dependencies = [
  "fasteners",
  "koda>=1.4",
  "PyFiglet",
  "beartype",
  "keyring; sys_platform=='win32'",
  "setproctitle",
]

[project.optional-dependencies]
tools = [
  "matplotlib",
  "pipe",
  "pyexcel_xls",
  "pyexcel_xlsx",
]

**Comment by ohaswin** [comment]
It's not the fact that pyscan couldn't detect the availability on PyPI, rather it didn't know which version to look for.
the only dependency in your pyproject.toml with a version seems to be for `koda`, all the others lack them.

Usually then, pyscan then looks at your `pip` to see if you installed it and gathers the version from there. But if not found on both cases, it errors (for now)

Pyscan will be able to get the latest stable version from pypi in the next version and prompt you wether you want to use it. But versonizing is expected (though not feasible for everyone) now.

**Comment by ArneBachmannDLR** [comment]
Sorry for being ignorant, I've just casually stumbled across this project!

As an idea, couldn't you look into the `site_packages` folder to derive the installed pip versions?

![Screenshot 2023-06-01 170643](https://github.com/aswinnnn/pyscan/assets/54819781/45dec9ba-5cb3-42e5-b709-7aa12490b730)

- koda 1.4
- kazoo 2.8.0
- etc.

**Comment by ohaswin** [comment]
That's an excellent way to derive the versions for sure, but site-packages seems to have modules that you have manually built or installed through pip, which means it would be visible through `pip list/show/freeze`. Pyscan uses a combination of that, but so I still have no idea how it failed to detect or crashed when it got to `koda`.

I can see from your `pyproject.toml` that you haven't mentioned a version for `fasteners` but it got detected through `pip` anyway, but failed to detect it when it came to `koda`, though the version is specified right in there. I wish I could dive deeper into this, but this seems like a combination of bugs that were just waiting to be detected or a fallible logic somewhere in pyscan.

You opening this issue just inspired me to dive into 3 or 4 different features/optimization pyscan needs, so I appreciate that. Sad to see that I couldn't exactly diagnose a concrete root the of the problem, though.

**Comment by ArneBachmannDLR** [comment]
Let me know if/how I can be of any assistance!
